#
# This generates Doxygen autodocs for the C++ API, based on work from libyui project
#

name: publish-api-doc

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

    - name: Create clean gh-pages branch
      run:  |
        git checkout -b gh-pages
        git submodule update --init --recursive

    - name: Install Doxygen
      run: sudo apt install doxygen graphviz

    - name: Install Vulkan
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: latest

    - name: Configure VulkanSceneGraph/vsgXchange etc.
      run: cmake -S . -B . -DCMAKE_BUILD_TYPE=Release

    - name: Build Documentation
      run: make -j 2 docs

    - name: Add generated autodocs to Git repo in the gh-pages branch
      run:  |
        git config --global user.email "robert@openscenegraph.com"
        git config --global user.name  "$GITHUB_WORKFLOW GitHub action"
        git add ref
        git commit -am "Generated API doc"

    - name: Publish autodocs as GitHub pages
      run:  git push -f origin gh-pages:gh-pages

    - name: Result URLs
      run:  |
        REPO_OWNER=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 1)
        REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2)
        echo "Formatted API docs:  https://$REPO_OWNER.github.io/$REPO_NAME"
        echo ""
        echo "GitHub pages branch: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/tree/gh-pages"
